# Generated by Django 2.2.3 on 2019-07-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('estimated_duration', models.IntegerField(blank=True)),
                ('importance', models.IntegerField(blank=True, verbose_name='Approximate importance, e.g. £ profit')),
                ('due_date', models.DateField(blank=True)),
            ],
        ),
    ]
