# Generated by Django 2.2.3 on 2019-07-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_task_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='estimated_duration',
            field=models.IntegerField(blank=True, verbose_name='Estimated duration (integer field, decide on a unit yourself per your use-case)'),
        ),
    ]
