# Generated by Django 2.2.3 on 2019-07-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_task_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='importance',
            field=models.IntegerField(blank=True, verbose_name='Approximate importance, e.g. how much you would pay to delegate it'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Task description'),
        ),
    ]
